#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SmartLoadControl.Resource", IsApplication=true)]

namespace SmartLoadControl
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int qos = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_AddDev_normal = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_AddDev_pressed = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_AddDev_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int spinner_ring = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070010
			public const int DevName = 2131165200;
			
			// aapt resource value: 0x7f070013
			public const int back_btn = 2131165203;
			
			// aapt resource value: 0x7f070002
			public const int btn_AddMod = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int btn_add_layer = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int btn_back = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int btn_find = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int devLay = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int frameLayoutRoot = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int frameRootLayer = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayout1 = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout_mod = 2131165188;
			
			// aapt resource value: 0x7f070012
			public const int ok_config_btn = 2131165202;
			
			// aapt resource value: 0x7f07000e
			public const int passText = 2131165198;
			
			// aapt resource value: 0x7f070008
			public const int progressBar2 = 2131165192;
			
			// aapt resource value: 0x7f070011
			public const int read_config_btn = 2131165201;
			
			// aapt resource value: 0x7f070003
			public const int scrollView1 = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int ssidText = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int textView1 = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int textView2 = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int textView6 = 2131165199;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ModConfig = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ModConfigNext = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int dev_config = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int qcancel = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int qdelete = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int qno = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int question = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int question1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int qyes = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int select_dev = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
